set search_path="I_NOTE";
create index "IDX_LB_TYPE_EVALUATION" ON "TB_TYPE_EVALUATION" USING BTREE
("LB_TYPE_EVALUATION");
--DROP INDEX IF EXISTS "IDX_NOM_PREN_ETUDIANT" ;
CREATE UNIQUE INDEX "IDX_NOM_PREN_ETUDIANT" 
ON "TB_ETUDIANT" USING BTREE ("NOM_ETUDIANT", "PREN_ETUDIANT");

CREATE INDEX "IDX_CIVILITE_ETUDIANT" ON "TB_TYPE_EVALUATION" USING BTREE ("LB_TYPE_EVALUATION");
CREATE INDEX "IDX_NOM_PREN_ENSEIGNANT" ON"TB_ENSEIGNANT" using btree ("NOM_ENSEIGNANT","PREN_ENSEIGNANT");
CREATE INDEX "IDX_LB_MATIERE" ON "TB_MATIERE" USING BTREE ("LB_MATIERE");
CREATE INDEX "IDX_DT_NOTE" ON "TB_NOTE" USING BTREE ("DT_NOTE");

